/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201801251438.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V0_COMMONAPI_EXAMPLES_E04_Phone_Book_DBUS_DEPLOYMENT_HPP_
#define V0_COMMONAPI_EXAMPLES_E04_Phone_Book_DBUS_DEPLOYMENT_HPP_

#include <commonapi/examples/E04PhoneBookDBusDeployment.hpp>

#include <commonapi/examples/E04PhoneBookDBusDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/DBus/DBusDeployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace commonapi {
namespace examples {
namespace E04PhoneBook_ {

// Interface-specific deployment types
typedef CommonAPI::MapDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StringDeployment
> phoneNumberMapDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::StringDeployment,
    CommonAPI::DBus::StringDeployment,
    CommonAPI::DBus::StringDeployment,
    CommonAPI::DBus::StringDeployment,
    CommonAPI::DBus::StringDeployment,
    CommonAPI::MapDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::DBus::StringDeployment
    >
> phoneBookStructDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> elementFilterStructDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StringDeployment
> contentFilterStructDeployment_t;

typedef CommonAPI::EmptyDeployment phoneBookDataElementDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::DBus::StringDeployment
> phoneBookDataElementStringDeployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::MapDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::DBus::StringDeployment
    >
> phoneBookDataElementPhoneNumberDeployment_t;

typedef CommonAPI::MapDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> phoneBookDataElementMapDeployment_t;


// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployments

// Broadcast-specific deployments


} // namespace E04PhoneBook_
} // namespace examples
} // namespace commonapi

#endif // V0_COMMONAPI_EXAMPLES_E04_Phone_Book_DBUS_DEPLOYMENT_HPP_
