/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201805221014.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include "E04PhoneBook.hpp"

namespace commonapi {
namespace examples {





std::shared_ptr< E04PhoneBook::phoneBookDataElement> E04PhoneBook::phoneBookDataElement::create(CommonAPI::Serial _serial) {
    switch (_serial) {
    case E04PhoneBook::PHONEBOOKDATAELEMENT_SERIAL:
        return std::make_shared< E04PhoneBook::phoneBookDataElement>();
    case E04PhoneBook::PHONEBOOKDATAELEMENTSTRING_SERIAL:
        return std::make_shared< E04PhoneBook::phoneBookDataElementString>();
    case E04PhoneBook::PHONEBOOKDATAELEMENTPHONENUMBER_SERIAL:
        return std::make_shared< E04PhoneBook::phoneBookDataElementPhoneNumber>();
    default:
        break;
    }
    return std::shared_ptr< E04PhoneBook::phoneBookDataElement>();
}




} // namespace examples
} // namespace commonapi
