/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201801251438.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <commonapi/examples/E04PhoneBook.hpp>
#include <commonapi/examples/E04PhoneBookDBusStubAdapter.hpp>

namespace commonapi {
namespace examples {

std::shared_ptr<CommonAPI::DBus::DBusStubAdapter> createE04PhoneBookDBusStubAdapter(
                   const CommonAPI::DBus::DBusAddress &_address,
                   const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< E04PhoneBookDBusStubAdapter<::commonapi::examples::E04PhoneBookStub>>(_address, _connection, std::dynamic_pointer_cast<::commonapi::examples::E04PhoneBookStub>(_stub));
}

void initializeE04PhoneBookDBusStubAdapter() {
    CommonAPI::DBus::Factory::get()->registerStubAdapterCreateMethod(
        E04PhoneBook::getInterface(), &createE04PhoneBookDBusStubAdapter);
}

INITIALIZER(registerE04PhoneBookDBusStubAdapter) {
    CommonAPI::DBus::Factory::get()->registerInterface(initializeE04PhoneBookDBusStubAdapter);
}

} // namespace examples
} // namespace commonapi
